from bot.base.resource import Template

UMAMUSUME_UI_TEMPLATE_PATH = "/umamusume/ui"
UMAMUSUME_BTN_TEMPLATE_PATH = "/umamusume/btn"
UMAMUSUME_REF_TEMPLATE_PATH = "/umamusume/ref"
UMAMUSUME_UMA_ICON_TEMPLATE_PATH = "/umamusume/uma_icon"

UI_PRESS_START = Template("PRESS_START", UMAMUSUME_UI_TEMPLATE_PATH)
UI_INFO = Template("INFO", UMAMUSUME_UI_TEMPLATE_PATH)
UI_MAIN_MENU = Template("MAIN_MENU", UMAMUSUME_UI_TEMPLATE_PATH)
UI_MAIN_MENU_CONTINUE = Template("MAIN_MENU_CONTINUE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_MAIN_MENU = Template("CULTIVATE/CULTIVATE_MAIN_MENU", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_TRAINING_SELECT = Template("CULTIVATE/CULTIVATE_TRAINING_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_TRAINING_SELECT_1 = Template("CULTIVATE/CULTIVATE_TRAINING_SELECT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_SCENARIO_SELECT = Template("CULTIVATE/CULTIVATE_SCENARIO_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_FOLLOW_SUPPORT_CARD_SELECT = Template("CULTIVATE/CULTIVATE_FOLLOW_SUPPORT_CARD_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_SUPPORT_CARD_SELECT = Template("CULTIVATE/CULTIVATE_SUPPORT_CARD_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_EXTEND_UMAMUSUME_SELECT = Template("CULTIVATE/CULTIVATE_EXTEND_UMAMUSUME_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_UMAMUSUME_SELECT = Template("CULTIVATE/CULTIVATE_UMAMUSUME_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_FINAL_CHECK = Template("CULTIVATE/CULTIVATE_FINAL_CHECK", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_EVENT_UMAMUSUME = Template("CULTIVATE/CULTIVATE_EVENT_UMAMUSUME", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_EVENT_SUPPORT_CARD = Template("CULTIVATE/CULTIVATE_EVENT_SUPPORT_CARD", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_EVENT_SCENARIO = Template("CULTIVATE/CULTIVATE_EVENT_SCENARIO", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_GOAL_RACE_1 = Template("CULTIVATE/CULTIVATE_GOAL_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_GOAL_RACE_2 = Template("CULTIVATE/CULTIVATE_GOAL_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_URA_RACE_1 = Template("CULTIVATE/CULTIVATE_URA_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_URA_RACE_2 = Template("CULTIVATE/CULTIVATE_URA_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_URA_RACE_3 = Template("CULTIVATE/CULTIVATE_URA_RACE_3", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RACE_LIST_1 = Template("CULTIVATE/CULTIVATE_RACE_LIST_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RACE_LIST_2 = Template("CULTIVATE/CULTIVATE_RACE_LIST_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_BEFORE_RACE_1 = Template("CULTIVATE/BEFORE_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_BEFORE_RACE_2 = Template("CULTIVATE/BEFORE_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_IN_RACE_UMA_LIST_1 = Template("CULTIVATE/IN_RACE_UMA_LIST_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_IN_RACE_UMA_LIST_2 = Template("CULTIVATE/IN_RACE_UMA_LIST_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_IN_RACE_1 = Template("CULTIVATE/IN_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_IN_RACE_2 = Template("CULTIVATE/IN_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_RACE_RESULT_1 = Template("CULTIVATE/RACE_RESULT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RACE_RESULT_2 = Template("CULTIVATE/RACE_RESULT_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RACE_REWARD_1 = Template("CULTIVATE/RACE_REWARD_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RACE_REWARD_2 = Template("CULTIVATE/RACE_REWARD_2", UMAMUSUME_UI_TEMPLATE_PATH)

# 青春杯比赛
UI_AOHARUHAI_RACE = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_RACE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_1 = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_2 = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_3 = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_RACE_3", UMAMUSUME_UI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_4 = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_RACE_4", UMAMUSUME_UI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_5 = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_RACE_5", UMAMUSUME_UI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_SELECT_OPPONENT = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_RACE_SELECT_OPPONENT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_FINAL_START = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_RACE_FINAL_START", UMAMUSUME_UI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_CONFIRM = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_RACE_CONFIRM", UMAMUSUME_UI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_INRACE = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_RACE_INRACE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_END = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_RACE_END", UMAMUSUME_UI_TEMPLATE_PATH)
UI_AOHARUHAI_RACE_SCHEDULE = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_RACE_SCHEDULE", UMAMUSUME_UI_TEMPLATE_PATH)

REF_AOHARUHAI_TEAM_NAME_0 = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_TEAM_NAME_0", UMAMUSUME_REF_TEMPLATE_PATH)
REF_AOHARUHAI_TEAM_NAME_1 = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_TEAM_NAME_1", UMAMUSUME_REF_TEMPLATE_PATH)
REF_AOHARUHAI_TEAM_NAME_2 = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_TEAM_NAME_2", UMAMUSUME_REF_TEMPLATE_PATH)
REF_AOHARUHAI_TEAM_NAME_3 = Template("CULTIVATE/AOHARUHAI/AOHARUHAI_TEAM_NAME_3", UMAMUSUME_REF_TEMPLATE_PATH)

REF_AOHARUHAI_TEAM_NAME = [REF_AOHARUHAI_TEAM_NAME_0, REF_AOHARUHAI_TEAM_NAME_1,
                           REF_AOHARUHAI_TEAM_NAME_2, REF_AOHARUHAI_TEAM_NAME_3]

UI_GOAL_ACHIEVED = Template("CULTIVATE/GOAL_ACHIEVED", UMAMUSUME_UI_TEMPLATE_PATH)
UI_GOAL_FAILED = Template("CULTIVATE/GOAL_FAILED", UMAMUSUME_UI_TEMPLATE_PATH)
UI_NEXT_GOAL = Template("CULTIVATE/NEXT_GOAL", UMAMUSUME_UI_TEMPLATE_PATH)
UI_ALL_GOAL_ACHIEVED = Template("CULTIVATE/ALL_GOAL_ACHIEVED", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_EXTEND = Template("CULTIVATE/CULTIVATE_EXTEND", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RESULT = Template("CULTIVATE/CULTIVATE_RESULT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RESULT_1 = Template("CULTIVATE/CULTIVATE_RESULT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RESULT_2 = Template("CULTIVATE/CULTIVATE_RESULT_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_CATCH_DOLL_GAME_1 = Template("CULTIVATE/CULTIVATE_CATCH_DOLL_GAME_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_CATCH_DOLL_GAME_2 = Template("CULTIVATE/CULTIVATE_CATCH_DOLL_GAME_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_CATCH_DOLL_GAME_3 = Template("CULTIVATE/CULTIVATE_CATCH_DOLL_GAME_3", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_CATCH_DOLL_GAME_RESULT_1 = Template("CULTIVATE/CULTIVATE_CATCH_DOLL_GAME_RESULT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_CATCH_DOLL_GAME_RESULT_2 = Template("CULTIVATE/CULTIVATE_CATCH_DOLL_GAME_RESULT_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_LEARN_SKILL_1 = Template("CULTIVATE/CULTIVATE_LEARN_SKILL_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_LEARN_SKILL_2 = Template("CULTIVATE/CULTIVATE_LEARN_SKILL_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_FINISH = Template("CULTIVATE/CULTIVATE_FINISH", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RECEIVE_CUP = Template("CULTIVATE/RECEIVE_CUP", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_LEVEL_RESULT = Template("CULTIVATE/CULTIVATE_LEVEL_RESULT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_FACTOR_RECEIVE = Template("CULTIVATE/FACTOR_RECEIVE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_HISTORICAL_RATING_UPDATE = Template("CULTIVATE/HISTORICAL_RATING_UPDATE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_SCENARIO_RATING_UPDATE = Template("CULTIVATE/SCENARIO_RATING_UPDATE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_ACTIVITY_RESULT = Template("CULTIVATE/ACTIVITY_RESULT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_ACTIVITY_REWARD = Template("CULTIVATE/ACTIVITY_REWARD", UMAMUSUME_UI_TEMPLATE_PATH)

REF_SUPPORT_CARD_TYPE_SPEED = Template("CULTIVATE/SUPPORT_CARD_TYPE_SPEED", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_STAMINA = Template("CULTIVATE/SUPPORT_CARD_TYPE_STAMINA", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_POWER = Template("CULTIVATE/SUPPORT_CARD_TYPE_POWER", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_WILL = Template("CULTIVATE/SUPPORT_CARD_TYPE_WILL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_INTELLIGENCE = Template("CULTIVATE/SUPPORT_CARD_TYPE_INTELLIGENCE", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_FRIEND = Template("CULTIVATE/SUPPORT_CARD_TYPE_FRIEND", UMAMUSUME_REF_TEMPLATE_PATH)


REF_TRAINING_TYPE_SPEED = Template("CULTIVATE/TRAINING_TYPE_SPEED", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TRAINING_TYPE_STAMINA = Template("CULTIVATE/TRAINING_TYPE_STAMINA", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TRAINING_TYPE_POWER = Template("CULTIVATE/TRAINING_TYPE_POWER", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TRAINING_TYPE_WILL = Template("CULTIVATE/TRAINING_TYPE_WILL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TRAINING_TYPE_INTELLIGENCE = Template("CULTIVATE/TRAINING_TYPE_INTELLIGENCE", UMAMUSUME_REF_TEMPLATE_PATH)

REF_MOTIVATION_1 = Template("CULTIVATE/MOTIVATION_1", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MOTIVATION_2 = Template("CULTIVATE/MOTIVATION_2", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MOTIVATION_3 = Template("CULTIVATE/MOTIVATION_3", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MOTIVATION_4 = Template("CULTIVATE/MOTIVATION_4", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MOTIVATION_5 = Template("CULTIVATE/MOTIVATION_5", UMAMUSUME_REF_TEMPLATE_PATH)

MOTIVATION_LIST = [REF_MOTIVATION_1, REF_MOTIVATION_2, REF_MOTIVATION_3, REF_MOTIVATION_4, REF_MOTIVATION_5]

REF_CULTIVATE_SUPPORT_CARD_EMPTY = Template("CULTIVATE/CULTIVATE_SUPPORT_CARD_EMPTY", UMAMUSUME_REF_TEMPLATE_PATH)
REF_FOLLOW_SUPPORT_CARD_DETECT_LABEL = Template("CULTIVATE/FOLLOW_SUPPORT_CARD_DETECT_LABEL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SELECTOR = Template("CULTIVATE/SELECTOR", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RACE_LIST_GOAL_RACE = Template("CULTIVATE/RACE_LIST_GOAL_RACE", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RACE_LIST_URA_RACE = Template("CULTIVATE/RACE_LIST_URA_RACE", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RACE_LIST_DETECT_LABEL = Template("CULTIVATE/RACE_LIST_DETECT_LABEL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SKILL_LIST_DETECT_LABEL = Template("CULTIVATE/SKILL_LIST_DETECT_LABEL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SKILL_LEARNED = Template("CULTIVATE/SKILL_LEARNED", UMAMUSUME_REF_TEMPLATE_PATH)

REF_DEBUT_RACE_NOT_WIN = Template("CULTIVATE/DEBUT_RACE_NOT_WIN", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUITABLE_RACE = Template("CULTIVATE/SUITABLE_RACE", UMAMUSUME_REF_TEMPLATE_PATH)

REF_RECOVER_TP_1 = Template("CULTIVATE/RECOVER_TP_1", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RECOVER_TP_2 = Template("CULTIVATE/RECOVER_TP_2", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RECOVER_TP_3 = Template("CULTIVATE/RECOVER_TP_3", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RECOVER_TP_4 = Template("CULTIVATE/RECOVER_TP_4", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RECOVER_TP_5 = Template("CULTIVATE/RECOVER_TP_5", UMAMUSUME_REF_TEMPLATE_PATH)

REF_FACTOR_DETECT_LABEL = Template("CULTIVATE/FACTOR_DETECT_LABEL", UMAMUSUME_REF_TEMPLATE_PATH)

URA_DATE_1 = Template("CULTIVATE/URA_DATE_1", UMAMUSUME_REF_TEMPLATE_PATH)
URA_DATE_2 = Template("CULTIVATE/URA_DATE_2", UMAMUSUME_REF_TEMPLATE_PATH)
URA_DATE_3 = Template("CULTIVATE/URA_DATE_3", UMAMUSUME_REF_TEMPLATE_PATH)

BTN_SKIP = Template("SKIP", UMAMUSUME_BTN_TEMPLATE_PATH)
BTN_SKIP_OFF = Template("SKIP_OFF", UMAMUSUME_BTN_TEMPLATE_PATH)
BTN_SKIP_SPEED_1 = Template("SKIP_SPEED_1", UMAMUSUME_BTN_TEMPLATE_PATH)
BTN_SKIP_SPEED_2 = Template("SKIP_SPEED_2", UMAMUSUME_BTN_TEMPLATE_PATH)
BTN_CLOSE = Template("CLOSE", UMAMUSUME_BTN_TEMPLATE_PATH)

UMA_ICON_URA_NPC_1 = Template("URA_NPC_1", UMAMUSUME_UMA_ICON_TEMPLATE_PATH)
UMA_ICON_URA_NPC_2 = Template("URA_NPC_2", UMAMUSUME_UMA_ICON_TEMPLATE_PATH)
UMA_ICON_FRIEND_1 = Template("FRIEND_1", UMAMUSUME_UMA_ICON_TEMPLATE_PATH)

UI_TEAM_STADIUM_RACE_1 = Template("TEAM_STADIUM/TEAM_STADIUM_RACE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_RACE_2 = Template("RACE_TITLE", UMAMUSUME_UI_TEMPLATE_PATH)

UI_TEAM_STADIUM_TITLE = Template("TEAM_STADIUM/TEAM_STADIUM_MAIN", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_MAIN_1 = Template("TEAM_STADIUM/TEAM_STADIUM_TEAM_RACE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_MAIN_2 = Template("TEAM_STADIUM/TEAM_STADIUM_RANK_BONUS", UMAMUSUME_UI_TEMPLATE_PATH)

UI_TEAM_STADIUM_SELECT_OPPONENT = Template("TEAM_STADIUM/TEAM_STADIUM_SELECT_OPPONENT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_BEFORE_RACE = Template("TEAM_STADIUM/TEAM_STADIUM_BEFORE_RACE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_CHECK_RESULT = Template("TEAM_STADIUM/TEAM_STADIUM_CHECK_RESULT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_CHECK_ALL_RESULTS = Template("TEAM_STADIUM/TEAM_STADIUM_CHECK_ALL_RESULTS", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_RESULTS = Template("TEAM_STADIUM/TEAM_STADIUM_RESULTS", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_REWARD = Template("TEAM_STADIUM/TEAM_STADIUM_REWARD", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_END = Template("TEAM_STADIUM/TEAM_STADIUM_END", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_ALL_RESULTS = Template("TEAM_STADIUM/TEAM_STADIUM_ALL_RESULTS", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_HIGH_SCORE = Template("TEAM_STADIUM/TEAM_STADIUM_HIGH_SCORE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_LEVEL = Template("TEAM_STADIUM/TEAM_STADIUM_LEVEL", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TEAM_STADIUM_CONTINUE = Template("TEAM_STADIUM/TEAM_STADIUM_CONTINUE", UMAMUSUME_UI_TEMPLATE_PATH)
REF_TEAM_STADIUM_OFF = Template("TEAM_STADIUM/TEAM_STADIUM_OFF", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TEAM_STADIUM_OFF2 = Template("TEAM_STADIUM/TEAM_STADIUM_OFF_2", UMAMUSUME_REF_TEMPLATE_PATH)

UI_TIME_SALE_1 = Template("TIME_SALE/TIME_SALE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TIME_SALE_2 = Template("TIME_SALE/TIME_SALE_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_TIME_SALE_3 = Template("TIME_SALE/TIME_SALE_3", UMAMUSUME_UI_TEMPLATE_PATH)
REF_TIME_SALE_BOUGHT = Template("TIME_SALE/TIME_SALE_BOUGHT", UMAMUSUME_REF_TEMPLATE_PATH)

UI_GUILD_MAIN = Template("DONATE/DONATE_GUILD_MAIN", UMAMUSUME_UI_TEMPLATE_PATH)
UI_GUILD_MAIN_2 = Template("DONATE/DONATE_GUILD_MAIN_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CIRCLE_RANKING_RESULT = Template("DONATE/CIRCLE_RANKING_RESULT", UMAMUSUME_UI_TEMPLATE_PATH)
REF_DONATE_REQUESTS = Template("DONATE/DONATE_REQUESTS", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DONATE_PLUS_UNAVAILABLE = Template("DONATE/DONATE_PLUS_UNAVAILABLE", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DONATE_ASKED = Template("DONATE/DONATE_ASKED", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DONATE_ASKED_INCOMPLETE = Template("DONATE/DONATE_ASKED_INCOMPLETE", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DONATE_ASKED_CLOSED = Template("DONATE/REF_DONATE_ASKED_CLOSED", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DONATE_ASKED_TIMEOUT = Template("DONATE/DONATE_ASKED_TIMEOUT", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DONATE_ASKING = Template("DONATE/DONATE_ASKING", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DONATE_ASK_CONFIRM = Template("DONATE/DONATE_ASK_CONFIRM", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DONATE_DONATED = Template("DONATE/DONATE_DONATED", UMAMUSUME_REF_TEMPLATE_PATH)
BTN_DONATE_AVAILABLE = Template("DONATE_AVAILABLE", UMAMUSUME_BTN_TEMPLATE_PATH)
REF_DONATE_UNAVAILABLE = Template("DONATE/DONATE_UNAVAILABLE", UMAMUSUME_REF_TEMPLATE_PATH)

UI_DAILY_SCHEDULE = Template("DAILY/DAILY_SCHEDULE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_DAILY_RACE_TITLE = Template("DAILY/DAILY_RACE_MAIN", UMAMUSUME_UI_TEMPLATE_PATH)
UI_DAILY_RACE_SELECT_RACER = Template("DAILY/DAILY_RACE_SELECT_RACER", UMAMUSUME_UI_TEMPLATE_PATH)
REF_DAILY_RACE_MULTI_RACE_ON = Template("DAILY/DAILY_RACE/DAILY_RACE_MULTI_RACE_ON", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DAILY_RACE_MULTI_RACE_OFF = Template("DAILY/DAILY_RACE/DAILY_RACE_MULTI_RACE_OFF", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DAILY_RACE_MOONLIGHT = Template("DAILY/DAILY_RACE/DAILY_RACE_MOONLIGHT", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DAILY_RACE_JUPITER = Template("DAILY/DAILY_RACE/DAILY_RACE_JUPITER", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DAILY_RACE_EASY = Template("DAILY/DAILY_RACE/DAILY_RACE_EASY", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DAILY_RACE_NORMAL = Template("DAILY/DAILY_RACE/DAILY_RACE_NORMAL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DAILY_RACE_HARD = Template("DAILY/DAILY_RACE/DAILY_RACE_HARD", UMAMUSUME_REF_TEMPLATE_PATH)
REF_DAILY_RACE_EXTREME = Template("DAILY/DAILY_RACE/DAILY_RACE_EXTREME", UMAMUSUME_REF_TEMPLATE_PATH)

DAILY_LEGEND_OPPONENT = {
    k: Template(f"DAILY/DAILY_LEGEND_RACE/{k}", UMAMUSUME_REF_TEMPLATE_PATH)
    for k in [
        101, 102, 103,
        201, 202, 203, 204,
        301, 302, 303,
        401, 402, 403, 404,
        501, 502, 503,
        601, 602, 603,
        701, 702, 703,
        801, 802, 803,
        901, 902, 903,
    ]
}

# 限时: 富士奇石的表演秀
FUJIKISEKI_SHOW_DIFFICULTY_LOCKED = Template("CULTIVATE/FUJIKISEKI_SHOW/DIFFICULTY_LOCKED", UMAMUSUME_UI_TEMPLATE_PATH)
FUJIKISEKI_SHOW_DIFFICULTY = [Template("CULTIVATE/FUJIKISEKI_SHOW/DIFFICULTY_1", UMAMUSUME_UI_TEMPLATE_PATH),
                              Template("CULTIVATE/FUJIKISEKI_SHOW/DIFFICULTY_2", UMAMUSUME_UI_TEMPLATE_PATH),
                              Template("CULTIVATE/FUJIKISEKI_SHOW/DIFFICULTY_3", UMAMUSUME_UI_TEMPLATE_PATH),
                              Template("CULTIVATE/FUJIKISEKI_SHOW/DIFFICULTY_4", UMAMUSUME_UI_TEMPLATE_PATH),
                              Template("CULTIVATE/FUJIKISEKI_SHOW/DIFFICULTY_5", UMAMUSUME_UI_TEMPLATE_PATH)]
UI_FUJIKISEKI_SHOW_MODE_RESULT_1 = Template("CULTIVATE/FUJIKISEKI_SHOW/SHOW_MODE_RESULT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_FUJIKISEKI_SHOW_MODE_RESULT_2 = Template("CULTIVATE/FUJIKISEKI_SHOW/SHOW_MODE_RESULT_2", UMAMUSUME_UI_TEMPLATE_PATH)
